server:
  port: 3344

spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
#          uri: https://github.com/explore11/cloud-config.git   使用这种地址的 需要ssl验证  可以使用skipSslValidation 跳过验证
#          skipSslValidation: true
          uri: git@github.com:explore11/cloud-config.git  #使用的是ssh的验证方式
          search-paths:
            - cloud-config
          default-label: master
#      rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    ip-address: cloud-config
    prefer-ip-address: true

# 利用消息总线实现自动刷新  配置完成后运维人员 执行curl -X POST "http://localhost:3344/actuator/bus-refresh"
# 动态刷新的定点通知 公式：http://localhost:配置中心的端口号/actuator/bus-refresh/{destination}
# eg: 只通知3355   curl -X POST  "http://localhost:3344/actuator/bus-refresh/config-client:3355"   服务名字:端口号
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

