server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/explore11/cloud-config.git   使用这种地址的 需要ssl验证  可以使用skipSslValidation 跳过验证
#          skipSslValidation: true
          uri: git@github.com:explore11/cloud-config.git  #使用的是ssh的验证方式
          search-paths:
            - cloud-config
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    ip-address: cloud-config
    prefer-ip-address: true
