server:
  port: 8001
spring:
  application:
    name: cloud-payment-com.atguigu.service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.entities

eureka:
  client:
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1     #每次发送心跳间隔时间
#    lease-expiration-duration-in-seconds: 2   #最后一次发送心跳后等待的时间

