server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启动态路由
      routes:
        - id: payment_route1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #        uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path= /payment/get/**  #断言,路径相匹配的进行路由
        #        - After=2020-03-24T23:02:33.056+08:00[Asia/Shanghai]
        #        - Before=2020-03-24T23:02:33.056+08:00[Asia/Shanghai]
        #        - Between=2020-03-24T22:02:33.056+08:00[Asia/Shanghai], 2020-03-24T23:02:33.056+08:00[Asia/Shanghai]


        - id: payment_route2 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #        uri: http://localhost:8001/ #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言,路径相匹配的进行路由
#        - Cookie=username,zzyy               curl http://localhost:9527/payment/lb  --cookie "username=zzyy"
#        - Query=username, \d+       curl  http://localhost:9527/payment/lb?username=11

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    ip-address: gateway9527


